In [5]:
import numpy as np
import open3d as o3d    

def main():
    cloud = o3d.io.read_point_cloud("Data/PLY/1.1.ply") # Read the point cloud
    o3d.visualization.draw_geometries([cloud]) # Visualize the point cloud     

if __name__ == "__main__":
    main()

In [17]:
if __name__ == "__main__":

    print("Load a ply point cloud, print it, and render it")
    pcd = o3d.io.read_point_cloud("Data/PLY/6.3.ply")
    print(pcd)
    print(np.asarray(pcd.points))
    o3d.visualization.draw_geometries([pcd])

    print("Downsample the point cloud with a voxel of 0.05")
    downpcd = pcd.voxel_down_sample(voxel_size=0.05)
    o3d.visualization.draw_geometries([downpcd])

Load a ply point cloud, print it, and render it
PointCloud with 156203 points.
[[-3.54101562  2.8203125  -4.95703125]
 [-3.53125     2.8203125  -4.95703125]
 [-3.53710938  2.83398438 -4.98046875]
 ...
 [-0.09210205 -0.42260742 -0.88134766]
 [-0.09014893 -0.42260742 -0.88134766]
 [ 3.01367188 -2.22460938 -4.640625  ]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
Downsample the point cloud with a voxel of 0.05


In [11]:
np.shape(np.asarray(pcd.points))

(299140, 3)